serokell/tzbot

package.yaml, src/TzBot/Parser.hs, tzbot.cabal
This implement `parseTimeRefs` to support a wide (but possibly not complete) array of time references from the given Text.
All the examples in the issues have been added as doctests.
Fixed #1
- Tests
- Haddock
=> [#1] Add time references parser

package.yaml, src/TzBot/Slack.hs, src/TzBot/Slack/API.hs, tzbot.cabal
Problem: `openConnection` endpoint isn't used because web-socket mode starts with the function `runSocketMode` from slacker-package. Therefore unused endpoint and corresponding functions can be safely removed.
Solution: remove unused endpoint and functions
=> remove unused endpoint and functions

package.yaml, src/TzBot/TimeReference.hs, test/Test/TzBot/TimeReferenceToUtcSpec.hs, tzbot.cabal
Problem: currently we can obtain time references via parsing but are not able to convert this references to a timestamp.
Solution: implement `timeReferenceToUTC` function
that converts time reference to a timestamp, possibly resulting in an error.
Fixed #2
- Tests
- Haddock
=> [#2] Convert time references to UTC

src/TzBot/BotMain.hs, src/TzBot/Config/Types.hs, src/TzBot/RunMonad.hs, src/TzBot/Slack.hs
Problem: datatype `BotConfig` was redundant.
Solution: use `Config` instead.
Fixed #6 
- Tests
- Haddock
=> [Fix] Remove redundant  `BotConfig` datatype

package.yaml, src/TzBot/BotMain.hs, src/TzBot/Config.hs, src/TzBot/ProcessEvent.hs, src/TzBot/Slack.hs, test/Test/TzBot/ConfigSpec.hs, test/Test/TzBot/HandleTooManyRequests.hs, tzbot.cabal
Problem: Sometimes slack can respond with status 429 Too Many Requests.
We have to handle this and take a try to request the slack api again
after the delay set in Retry-After header.
Solution: Wrap enent handler with function which detects the response
with status code 429, extracts the delay from headers and runs again the
event handler after the delay. The number of attempts is defined in bot
configuration.
Fixed #5 
- Tests
- Haddock
=> Handle 429 Too Many Requests

package.yaml, src/TzBot/Slack.hs, src/TzBot/Slack/API.hs, tzbot.cabal
Problem: Some Slack methods are paginated and hence can return not all objects if the limit turns out to be less than total amount of the objects.
Solution: Handle pagination by cursor following, fetching all available objects.
Fixed #8 
- Tests
- Haddock
=> [#8] Handle Slack pagination

manifest.yml, package.yaml, src/TzBot/BotMain.hs, src/TzBot/Cache.hs, src/TzBot/Config.hs, src/TzBot/Config/Default.hs, src/TzBot/Config/Types.hs, src/TzBot/Instances.hs, src/TzBot/Parser.hs, src/TzBot/ProcessEvent.hs, src/TzBot/RunMonad.hs, src/TzBot/Slack.hs, src/TzBot/Slack/API.hs, src/TzBot/Slack/EphemeralMessage.hs, src/TzBot/Slack/Events.hs, src/TzBot/Util.hs, test/Test/TzBot/ConfigSpec.hs, test/Test/TzBot/TimeReferenceToUtcSpec.hs, tzbot.cabal
Problem: The bot uses two methods, `getUser` and `getChannelMembers`, which are subjects to Slack's rate limits, and we need to avoid unneeded calls to those methods.
Solution: Add caching for user info and channel members.
Fixed #7
- Tests
- Haddock
=> [#7] Cache slack data

src/TzBot/ProcessEvent.hs
Problem: Currently, we run getUser sequentially on all the users of the channel, and that may cause large delays.
Solution: Put `getUserInfoCached` and `sendEphemeralMessage` in separate thread.
Fixed #35 
- Tests
- Haddock
=> [#35] Fetch user info concurrently

config/config.yaml, manifest.yml, src/TzBot/Config.hs, src/TzBot/Config/Default.hs, src/TzBot/Config/Types.hs, src/TzBot/ProcessEvents.hs, src/TzBot/ProcessEvents/BlockAction.hs, src/TzBot/ProcessEvents/Command.hs, src/TzBot/ProcessEvents/Message.hs, src/TzBot/Slack/Events.hs, src/TzBot/Slack/Fixtures.hs, src/TzBot/Util.hs, test/Test/TzBot/ConfigSpec.hs, tzbot.cabal
Problem: Currently, each ephemeral with translations contain button which functionality doubles existing entrypoint. Because it can be annoying, we should remove it and instead give a hint to a user how to call tzbot entrypoints.
Solution: Remove buttons from ephemerals, add command /tzhelp, append the usage of that command randomly with rather low chance to ephemerals with translations.
Also done:
* Add dev mode using undocumented envvar;
* Handle messages with unknown subtype as ordinary messages.
Fixed #44, #41
- Tests
- Haddock
=> [#44] Add help command

package.yaml, src/TzBot/ProcessEvents/Common.hs, src/TzBot/ProcessEvents/Message.hs, src/TzBot/Slack/API.hs, src/TzBot/Slack/API/MessageBlock.hs, src/TzBot/Util.hs, test/Test/TzBot/MessageBlocksSpec.hs, tzbot.cabal
Problem: The bot should ignore time references in code blocks because they are most probably some logs or just some code quotations.
Solution: Ignore codeblocks by analyzing (undocumented) block structure of incoming Slack messages, using some simple code ignoring function when the block structure cannot be parsed.
Fixed #38
- Tests
- Haddock
=> [#38] Ignore time references in code blocks

src/TzBot/Feedback/Save.hs, src/TzBot/ProcessEvents/Message.hs, src/TzBot/Render.hs, src/TzBot/Slack/API/Block.hs, src/TzBot/Slack/Modal.hs, src/TzBot/TimeReference.hs, test/Test/TzBot/TimeReferenceToUtcSpec.hs
We are going to work hard on translate/render modules and I would like some refactor to be present in all of that PRs beforehand.
Changes:
1. Remove button from section builders as it's never needed;
2. Add separate datatype for sender flag instead of plain Bool;
3. Replace plain text with markdown in the Slack section block;
4. Add functions for converting to offset time/back;
5. Unite fields of TimeReferenceToUtcResult for convenience.
Fixed #
- Tests
- Haddock
=> [Fix] Slight refactor of render part

package.yaml, src/TzBot/BotMain.hs, src/TzBot/Cache.hs, src/TzBot/Feedback/Dialog.hs, src/TzBot/Logger.hs, src/TzBot/ProcessEvents.hs, src/TzBot/ProcessEvents/Message.hs, src/TzBot/Render.hs, src/TzBot/RunMonad.hs, src/TzBot/Slack.hs, src/TzBot/Slack/API.hs, src/TzBot/Util.hs
Problem: Currently message_changed event is handled by translating new time references and sending ephemeral with them, which can be inconvenient sometimes.
Solution: On message_changed event send an ephemeral containing message permalink and all message time references translated.
Fixed #22
- Tests
- Haddock
=> [#22] Revise messages editing

package.yaml, src/TzBot/Cache.hs, src/TzBot/Feedback/Save.hs, src/TzBot/ProcessEvents.hs, src/TzBot/ProcessEvents/Message.hs, src/TzBot/RunMonad.hs, src/TzBot/Slack.hs, src/TzBot/Util.hs, tzbot.cabal
Problem: Currently we use `ExceptT BotException IO` which is inconvenient because both BotException, other sync exceptions and async exceptions should be handled separately.
Solution: Remove ExceptT, use UnliftIO for exceptions handling, also use UnliftIO for asyncs instead of monad-control.
Fixed #51
- Tests
- Haddock
=> [#51] Revise exceptions handling

src/TzBot/BotMain.hs, src/TzBot/Slack/Events.hs
Problem: Right now, we're using `withFile` to open a file handle to `feedback.log`. This seems to use `BlockBuffering` by default, which means feedback is not immediately written to the log file. This might take some time to be written to file or, worst case scenario, is only written when the application shuts down.
Solution: Use line buffering instead, so that output is flushed to the file as soon as a newline character is emitted.
Also took the opportunity to do a couple of small fixes: replace a usage of `withObject ""` with `withObject "MessageEvent"`, and pull dependencies from hackage instead of github repos.
Fixed #68
- Tests
- Haddock
=> [#68] Flush feedback to the file immediately

src/TzBot/Render.hs, src/TzBot/Slack/API.hs, src/TzBot/TimeReference.hs, test/Test/TzBot/RenderSpec.hs, test/Test/TzBot/TimeReferenceToUtcSpec.hs, tzbot.cabal
Problem: Full date is not shown for the original time reference, which
can be useful for receivers.
Solution: Append inferred parts of the date to the quoted original time
reference text.
Fixed #36 
- Tests
- Haddock
=> [#36] Append inferred date parts

src/TzBot/ProcessEvents/Common.hs, src/TzBot/ProcessEvents/Message.hs, src/TzBot/Render.hs, src/TzBot/Util.hs, test/Test/TzBot/RenderSpec.hs
Problem: Sometimes, when timezones in message and a receiver's one are the same, it's not required to actually translate anything because the original time reference is already relevant for the receiver.
Solution: for other users than sender, say "timezone is the same", for sender himself translate only time references that are in other timezones and ignore ones with his timezone, but translate everything when modal is triggered.
Fixed #53 
- Tests
- Haddock
=> [#53] Skip sending for matching timezones

package.yaml, src/TzBot/Parser.hs, src/TzBot/Render.hs, src/TzBot/TimeReference.hs, test/Test/TzBot/RenderSpec.hs, test/Test/TzBot/TimeReferenceToUtcSpec.hs, tzbot.cabal
Problem: Currently, unrecognized timezone abbreviation is simply ignored as it would be an unrelated word.
Solution: Consider all-capitalized words with 2-5 characters length as timezone abbreviations and warn users when they are not known by us; add hints when encountered abbreviation is similar to some of known ones.
Fixed #70 
- Tests
- Haddock
=> [#70] Warn users on unrecognized timezone abbreviation

src/TzBot/Render.hs, src/TzBot/TimeReference.hs, test/Test/TzBot/RenderSpec.hs
Problem: Timezone abbreviations can be ambiguous, so we need to provide
comprehensive information about inferred timezone abbreviation in order
to prevent users confusion.
Solution: For timezone abbreviations, ephemerals explicitly state
timezone abbreviation info.
Fixed #71 
- Tests
- Haddock
=> [#71] Explicitly state offset for abbrevs

package.yaml, src/TzBot/Render.hs, src/TzBot/TimeReference.hs, test/Test/TzBot/TimeReferenceToUtcSpec.hs, tzbot.cabal
Problem: We use two different code branches for cases of static offset and timezone.
Solution: Unify two branches in timeReferenceToUTC.
Fixed #67 
- Tests
- Haddock
=> [#67] Refactor timeReferenceToUTC

.buildkite/pipeline.yml, src/TzBot/Render.hs, src/TzBot/TZ.hs, src/TzBot/TimeReference.hs, src/TzBot/Util.hs, test/Test/TzBot/GetTimeshiftsSpec.hs, test/Test/TzBot/RenderSpec.hs, test/Test/TzBot/TimeReferenceToUtcSpec.hs, tzbot.cabal
Problem: In some cases the bot selects the date rather arbitrarily, and if a timeshift is somewhere around, the translation may be dependent on concrete date. We should warn a user about possible timeshifts.
Solution: For some types of date references, also compute a date range to check for the possible timeshift, and report to user if something found.
Fixed part of #36
- Tests
- Haddock
=> [#36] Warn user on possible timeshifts

.buildkite/pipeline.yml, .gitignore, Makefile, README.md, docs/development.md, package.yaml, src/TzBot/Parser.hs, src/TzBot/ProcessEvents/Message.hs, src/TzBot/Render.hs, src/TzBot/TimeReference.hs, src/TzBot/Util.hs, test/Test/TzBot/GetTimeshiftsSpec.hs, test/Test/TzBot/ParserSpec.hs, tzbot.cabal
Problem: If a user writes "I'll be available around 10am-11am UTC", 10am has no location reference.
Solution: Add support for simple hyphenated and slashed intervals sharing all other context, resulting two different time references that are processed separately further. Also added conjugations via "and" and "or".
Fixed #79, partly fixed #16
- Tests
- Haddock
=> [#79] Add support for hyphenated intervals

package.yaml, src/TzBot/Parser.hs, src/TzBot/Util.hs, test/Test/TzBot/ParserSpec.hs, tzbot.cabal
The parser is quite hard to read/maintain.
This PR refactors parts of the browser to be more readable, and adds doctests for most parser sub-components to make it easier to understand what each of them do and how they're composed together.
None
- Tests
- Haddock
=> Refactor parser and improve docs/tests

src/TzBot/Parser.hs, test/Test/TzBot/ParserSpec.hs
The parser was accepting `7hff` and then defaulting `ff` to `0 minutes`.
Fixed #89
- Tests
- Haddock
=> [#89] Fix parsing of minutes after `h` separator

src/TzBot/BotMain.hs, src/TzBot/Cache.hs, src/TzBot/Config.hs, src/TzBot/Feedback/Dialog/Types.hs, src/TzBot/Feedback/Save.hs, src/TzBot/Parser.hs, src/TzBot/ProcessEvents/BlockAction.hs, src/TzBot/ProcessEvents/ChannelEvent.hs, src/TzBot/ProcessEvents/Command.hs, src/TzBot/ProcessEvents/Common.hs, src/TzBot/ProcessEvents/Interactive.hs, src/TzBot/Render.hs, src/TzBot/RunMonad.hs, src/TzBot/Slack/API/MessageBlock.hs, src/TzBot/TimeReference.hs
Problem: Matching with `RecordWildCards` can be problematic.
1. It makes it harder to see where identifiers come from. E.g.:
```
f x y D{..} = 
z
```
Where does `z`` come from? Is it a free variable? Or was it put in scope by `D{..}`? It's not clear.
2. It also makes it hard to see _where_ a variable is used in the definition of a function.
```
f x y z = 
< huge function definition >
```
If I want to know where and how `x` is used, I can just click it and my IDE will highlight all the places where `x` is used.
With `D{..}`, no such luck. I usually have to delete `D{..}` and then HLS will point me to where all the fields names no longer typecheck.
Solution: Replace usages of `RecordWildCards` with the recently introduced `OverloadedRecordDot` or `NamedFieldPuns`.
None
- Tests
silently …
=> [Chore] Avoid `RecordWildCards`

docs/implementation_details.md, src/TzBot/ProcessEvents/Message.hs
Problem: At the moment, when we receive a "message edited" event, and if the old message is not in our cache or it did not contain time references, we ignore the event:
```
-- if not found or expired, just ignore this message 
-- it's too old or just didn't contain any time refs
```
However, it's important to handle these events even when a message is not in the cache. For example:
1. A user types "let's meet at 7" and then amends "7" to "7am". The old message did not contain time refs, but the new one does, so we should handle that.
2. The server is restarted, we'll lose our cache. When the server is back up, we should still react when messages that were sent before the restart are edited.
Solution: If the old message's time refs are not found in the cache, inspect the `previous_message` …
=> [#93] Handle edited events when old message is not in cache

README.md, src/TzBot/BotMain.hs, src/TzBot/Cache.hs, src/TzBot/ProcessEvents.hs, src/TzBot/ProcessEvents/Common.hs, src/TzBot/Slack/API.hs, src/TzBot/Util.hs, test/Test/TzBot/Slack/API/Parser.hs, tzbot.cabal
Problem: The parser fails to parse events of type `message` and subtype
`channel_join`, and the logs are flooded with errors.
This seems to happen because the parser expects every event of type
`message` to have a `blocks` field, and that's not always true.
Solution: Make the `blocks` field optional.
Fixed #107
- Tests
- Haddock
=> [#107] Correctly parse `channel_join` events

src/TzBot/Logger.hs, src/TzBot/ProcessEvents/Message.hs
Problem: The `MessageContext` data type adds a `message_id` label to log messages, so we can identify which Slack message the server was processing when the log event occurred.
However, a message ID (or message timestamp, really) is not enough to identify a message. A message is uniquely identified by the `(timestamp, channel_id)` pair.
Solution: Add a `channel_id` label to `MessageContext`.
Fixed #109
- Tests
- Haddock
=> [#109] Enhance `MessageContext`

.github/pull_request_template.md, src/TzBot/Parser.hs
Problem: A slack message may sometimes contain multiple instances of the same time reference. When this happens, the ephemeral message will show the same entry twice.
Solution: ignore duplicated time references.
Fixed #110
- Tests
- Haddock
=> [#110] Deduplicate time references

src/TzBot/Render.hs, test/Test/TzBot/RenderSpec.hs
Problem: For users in, let's say, Tallinn, the ephemeral message will say `<time> <date> in Europe/Athens`. Technically, Tallinn and Athens are on the same offset, but this message may be confusing for some users.
Solution: Amend the message to instead say `<time> <date> in your timezone (Europe/Athens)`.
Fixed #111
- Tests
- Haddock
=> [#111] Improve ephemeral message phrasing

src/TzBot/ProcessEvents/Common.hs, src/TzBot/ProcessEvents/Message.hs, src/TzBot/Render.hs, test/Test/TzBot/RenderSpec.hs
Problem: We received some feedback that showing "You are in this timezone" in ephemeral messages isn't very useful.
It would be better to just display the converted time, like we do for all other ephemeral messages, for consitency.
Solution: display the converted time.
Fixed #112
- Tests
- Haddock
=> [#112] Do not display "You are in this timezone"

package.yaml, src/TzBot/Slack/API/MessageBlock.hs, test/Test/TzBot/MessageBlocksSpec.hs, tzbot.cabal
Problem: right now, when find an emoji block in a message, we split the
message in two. This means this message:
```
Hey, let's meet at 10:30 :clock1: tomorrow?
```
Will be interpreted as two separate sentences, `["Hey, let's meet at
10:30", "tomorrow?"]`, and "tomorrow" won't be taken into account.
Solution: skip over emoji blocks, and collate adjacent text-like blocks.
This is now parsed as a single sentence `["Hey, let's meet at 10:30
tomorrow?"]`
----
Problem: The server reports warnings whenever it finds a message with a
tag like `@user`. Since this occurs very often, it ends up flooding the
logs.
Solution: Don't report warnings for blocks of type `user`, `usergroup`
and `broadcast`.
Fixed part of #108
- Tests
- …
=> [#108] Improve block support

src/TzBot/ProcessEvents/Message.hs, src/TzBot/Slack/API/MessageBlock.hs, src/TzBot/Slack/Events.hs, test/Test/TzBot/Slack/API/Parser.hs
Whenever a user posts a message with a link, and Slack subsequently displays a preview of that URL, an event is sent to the server, and the server fails to parse it.
This PR fixes that and adds the `MDMessageUrlUnfurl` constructor.
Fixed part of #108
- Tests
- Haddock
=> [#108] Handle messages with link previews

.github/workflows/check.yml
Problem: We want to be able to run CI checks on PRs from external forks.
However, this is only possible with 'on: pull_request', while currently
CI is triggered 'on: push'
Solution: Change CI triggering condition to 'on: pull_request'.
Fixed #
- Tests
- Haddock
=> [Chore] Run CI checks on 'pull_request'

module.nix
Problem: By default, systemd services generated from the NixOS system configuration don't attempt to restart on failure since Restart=no. However, in some cases, running processes can fail for unclear reasons, and the simplest way to bring the failed service back to life is to restart it. Instead, currently, the service will fail and trigger an alert without attempting to restart.
Solution: Add default values for startLimitBurst, startLimitIntervalSec, Restart, and RestartSec.
Fixed #
- Tests
- Haddock
=> [Chore] Add systemd unit restart policy

flake.lock, module.nix
Problem: We want to harden the security of our systemd services.
Solution: Use the hardening profile defined in serokell.nix.
Fixed #
- Tests
- Haddock
=> [OPS-1161] Harden systemd service

module.nix
Properly import helpers used for tzbot service hardening.
Fixed #
- Tests
- Haddock
=> [Chore] Hotfix module hardening
